language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - valgrind
      - check
      - python3.4
before_install:
  - curl -L https://static.rust-lang.org/rustup.sh | sh -s -- --channel=stable --yes --prefix=$PWD --disable-sudo
  - export PATH=$PATH:$PWD/bin
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/lib
  - mkdir $HOME/bin && ln -s $(which python3.4) $HOME/bin/python3 && export PATH="$HOME/bin:$PATH"
script:
  - mvn checkstyle:check
  - mvn clean test -q
after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
os:
  - linux
  - osx
jdk:
  - oraclejdk8
  - oraclejdk7
matrix:
  allow_failures:
    - os: osx
