sudo: false
cache:
  directories:
    - $HOME/.m2
language: java
before_install:
  - ./before_install.sh
script:
  - mvn clean test
  - mvn verify
after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
